# Generated by Django 4.1.3 on 2024-02-15 16:34

import Home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comp', models.CharField(default='Company', max_length=150)),
                ('Durt', models.CharField(default='2020', max_length=100)),
                ('Abut', models.TextField(default='Etc', max_length=500)),
                ('Acct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Project', max_length=100)),
                ('Dscrp', models.TextField(default='Etc', max_length=500)),
                ('Cover', models.CharField(default='Img', max_length=200)),
                ('Acct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Some Name', max_length=100)),
                ('Work', models.CharField(default='Some Work', max_length=100)),
                ('PPic', Home.models.CloudinaryField(max_length=255, verbose_name='Profile')),
                ('Abut', models.TextField(default='Description', max_length=500)),
                ('Acct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Lang', max_length=100)),
                ('Dsrp', models.TextField(default='Etc', max_length=500)),
                ('Icon', Home.models.CloudinaryField(max_length=255, verbose_name='Lang')),
                ('Acct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inst', models.CharField(default='Institute', max_length=150)),
                ('Durt', models.CharField(default='2020', max_length=100)),
                ('Abut', models.TextField(default='Etc', max_length=500)),
                ('Acct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(default='Rando', max_length=100)),
                ('Source', models.CharField(default='Linkie', max_length=250)),
                ('Acct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(default='Rando', max_length=100)),
                ('Link', models.CharField(default='', max_length=250)),
                ('Icon', Home.models.CloudinaryField(max_length=255, verbose_name='Icon')),
                ('Acct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
