# Generated by Django 4.1.3 on 2024-02-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_project_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Cover',
            field=models.CharField(default='Img', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='Lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.lang'),
        ),
    ]
