# Generated by Django 4.1.3 on 2024-02-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_project_cover_project_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Lang',
        ),
        migrations.AddField(
            model_name='project',
            name='Lang',
            field=models.ManyToManyField(default=1, to='Home.lang'),
        ),
    ]
