# Generated by Django 4.1.3 on 2024-03-26 12:36

import Home.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_project_lang_project_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Cover',
            field=Home.models.CloudinaryField(max_length=255, verbose_name='Projects'),
        ),
    ]
