# Generated by Django 4.1.3 on 2024-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_project_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='Cred',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
