# Generated by Django 4.1.3 on 2024-04-09 04:58

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_lang_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Git',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='Link',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='lang',
            name='Icon',
            field=Home.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='Cover',
            field=Home.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='Lang',
            field=models.ManyToManyField(to='Home.lang'),
        ),
    ]
